# ==============================================================================
# SITE SETTINGS
# ==============================================================================
title: Andy Arditi
email: andyrdt@gmail.com
description: >-
  Personal academic website focused on research in AI, cryptography, and more.
baseurl: ""
url: "andyrdt.github.io"

# Social media
twitter_username: andyarditi

# ==============================================================================
# BUILD SETTINGS
# ==============================================================================
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar

# ==============================================================================
# NAVIGATION
# ==============================================================================
nav_items:
  - title: About
    url: /about
  - title: Research
    url: /research

# ==============================================================================
# CONTENT COLLECTIONS
# ==============================================================================
collections:
  pages:
    output: true
  papers:
    output: true
  notes:
    output: true
  posts:
    output: true

# ==============================================================================
# INCLUDE FILES IN BUILD
# ==============================================================================
include:
  - .well-known

# ==============================================================================
# EXCLUDE FILES FROM PROCESSING
# ==============================================================================
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - CODEBASE.md
  - .git/
  - .gitignore
